"""Add event_name to Event model

Revision ID: 49baec0f1115
Revises: 
Create Date: 2025-01-06 16:02:30.167987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49baec0f1115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('event_date', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###
